version: '3.1'

services:
  zoo:
    hostname: zoo
    build: .
    ports:
      - "2181:2181"
    environment:
      server.1: zoo:2888:3888
    command: /scripts/start_zk.sh
    
  init:
    hostname: init
    build: .
    environment:
      clusterName: rennes
      zkServers: "zoo:2181"
      configurationStore: "zoo:2181"
      pulsarNode: broker
      webServicePort: "8090"
      brokerServicePort: "6660"
    command: /scripts/init_cluster.sh
    depends_on:
      - zoo

  bookie:
    hostname: bookie
    build: .
    ports:
      - "3181:3181"
    environment:
      zookeeperServers: "zoo:2181"
      clusterName: rennes
    command: /scripts/start_bookie.sh
    depends_on:
      - init
    
  broker:
    hostname: broker
    build: .
    ports:
      - "6660:6650"
      - "8090:8080"
    environment:
      zookeeperServers: "zoo:2181"
      clusterName: rennes
      configurationStore: "zoo:2181"
    command: /scripts/start_broker.sh
    depends_on:
      - bookie

  proxy:
    hostname: proxy
    build: .
    ports:
      - "6650:6650"
      - "8080:8080"
    environment:
      zookeeperServers: "zoo:2181"
      clusterName: rennes
      configurationStore: "zoo:2181"
    command: /scripts/start_proxy.sh
    depends_on:
      - broker