version: '2.1'

services:
  zoo:
    hostname: zoo
    image: apachepulsar/pulsar:2.4.1
    ports:
      - "2181:2181"
    environment:
        ZK_ID: 1
        PULSAR_ZK_CONF: /conf/zookeeper.conf
    volumes:
      - ./conf:/conf
      - ./scripts:/scripts
    command: bin/pulsar zookeeper
    
  init:
    hostname: init
    image: apachepulsar/pulsar:2.4.1
    volumes:
      - ./conf:/conf
      - ./scripts:/scripts
    command: bin/pulsar initialize-cluster-metadata \
          --cluster pulsar-cluster \
          --zookeeper zoo:2181 \
          --web-service-url localhost:8080 \
          --configuration-store zoo:2181 \
          --broker-service-url pulsar://broker:6650
    depends_on:
      - zoo

  bookie:
    hostname: bookie
    image: apachepulsar/pulsar:2.4.1
    ports:
      - "3181:3181"
    environment:
        BOOKIE_CONF: /conf/bookkeeper.conf
    volumes:
      - ./conf:/conf
      - ./scripts:/scripts
    command: bin/bookkeeper bookie
    depends_on:
      - init
    
  broker:
    hostname: broker
    image: apachepulsar/pulsar:2.4.1
    environment:
        PULSAR_BROKER_CONF: /conf/broker.conf
    ports:
      - "6660:6650"
      - "8090:8080"
    volumes:
      - ./conf:/conf
      - ./scripts:/scripts
    command: bin/pulsar broker
    depends_on:
      - bookie


  pulsar-proxy:
    image: apachepulsar/pulsar:2.4.1
    hostname: pulsar-proxy
    ports:
      - "6650:6650"
      - "8080:8080"
    environment:
        PULSAR_PROXY_CONF: "/conf/proxy.conf"
    volumes:
      - ./conf:/conf
      - ./scripts:/scripts
    command: bin/pulsar proxy 
    depends_on:
      - broker

  # broker2:
  #   image: apachepulsar/pulsar:2.4.1
  #   hostname: broker2
  #   environment:
  #       PULSAR_BROKER_CONF: /conf/broker.conf
  #   ports:
  #     - "6661:6650"
  #     - "8091:8080"
  #   volumes:
  #     # - ./broker2/data:/pulsar/data/broker/
  #     # - ./broker2/log/:/pulsar/logs
  #     - ./conf:/conf
  #     - ./scripts:/scripts
  #   command: /bin/bash "/scripts/start_broker.sh"
  #   depends_on:
  #     - bookie1
  #     - bookie2
  #     - bookie3

  # zoo2:
  #   image: apachepulsar/pulsar:2.4.1
  #   hostname: zoo2
  #   ports:
  #     - "2182:2181"
  #   environment:
  #       ZK_ID: 2
  #       PULSAR_ZK_CONF: /conf/zookeeper.conf
  #   volumes:
  #   volumes:
  #     # - ./zoo2/data:/pulsar/data/zookeeper/
  #     # - ./zoo2/log/:/pulsar/logs
  #     - ./conf:/conf
  #     - ./scripts:/scripts
  #   command: /bin/bash "/scripts/start_zk.sh"

  # zoo3:
  #   image: apachepulsar/pulsar:2.4.1
  #   hostname: zoo3
  #   ports:
  #     - "2183:2181"
  #   environment:
  #       ZK_ID: 3
  #       PULSAR_ZK_CONF: /conf/zookeeper.conf
  #   volumes:
  #     # - ./zoo3/data:/pulsar/data/zookeeper/
  #     # - ./zoo3/log/:/pulsar/logs
  #     - ./conf:/conf
  #     - ./scripts:/scripts
  
  # bookie:
  #   image: apachepulsar/pulsar:2.4.1
  #   hostname: bookie
  #   ports:
  #     - "3182:3181"
  #   environment:
  #       BOOKIE_CONF: /conf/bookkeeper.conf
  #   volumes:
  #     # - ./bookie2/data:/pulsar/data/bookkeeper/
  #     # - ./bookie2/log/:/pulsar/logs
  #     - ./conf:/conf
  #     - ./scripts:/scripts
  #   command: /bin/bash "/scripts/start_otherbk.sh"
  #   depends_on:
  #     - bookie1

  # bookie3:
  #   image: apachepulsar/pulsar:2.4.1
  #   hostname: bookie3
  #   ports:
  #     - "3183:3181"
  #   environment:
  #       BOOKIE_CONF: /conf/bookkeeper.conf
  #   volumes:
  #     # - ./bookie3/data:/pulsar/data/bookkeeper/
  #     # - ./bookie3/log/:/pulsar/logs
  #     - ./conf:/conf
  #     - ./scripts:/scripts
  #   command: /bin/bash "/scripts/start_otherbk.sh"
  #   depends_on:
  #     - bookie1
  #   command: /bin/bash "/scripts/start_zk.sh"