version: '3.1'

networks:
  pulsar:
    driver: bridge

services:
  zoo:
    hostname: zoo
    build: .
    environment:
      server.1: zoo:2888:3888
    command: /scripts/start_zk.sh
    networks:
      - pulsar
    
  init:
    hostname: init
    build: .
    environment:
      clusterName: rennes
      zkServers: "zoo:2181"
      configurationStore: "zoo:2181"
      pulsarNode: broker
      webServicePort: "8080"
      brokerServicePort: "6650"
    command: /scripts/init_cluster.sh
    depends_on:
      - zoo
    networks:
      - pulsar

  bookie-cesson:
    hostname: bookie-cesson
    build: .
    environment:
      zookeeperServers: "zoo:2181"
      clusterName: rennes
    command: /scripts/start_bookie.sh
    depends_on:
      - init
    networks:
      - pulsar

  bookie-saint-jacques:
    hostname: bookie-saint-jacques
    build: .
    environment:
      zookeeperServers: "zoo:2181"
      clusterName: rennes
    command: /scripts/start_bookie.sh
    depends_on:
      - init
    networks:
      - pulsar
    
  broker:
    hostname: broker
    build: .
    environment:
      zookeeperServers: "zoo:2181"
      clusterName: rennes
      configurationStore: "zoo:2181"
    command: /scripts/start_broker.sh
    depends_on:
      - bookie-saint-jacques
      - bookie-cesson
    networks:
      - pulsar

  proxy:
    hostname: proxy
    build: .
    ports:
      - "6650:6650"
      - "8080:8080"
    environment:
      zookeeperServers: "zoo:2181"
      clusterName: rennes
      configurationStore: "zoo:2181"
    command: /scripts/start_proxy.sh
    depends_on:
      - broker
    networks:
      - pulsar