version: '3.1'

services:
  zoo:
    hostname: zoo
    image: apachepulsar/pulsar:2.8.1
    ports:
      - "2181:2181"
    environment:
        ZK_ID: 1
        PULSAR_ZK_CONF: /conf/zookeeper.conf
    volumes:
      - ./conf:/conf
      - ./scripts:/scripts
    command: bin/pulsar zookeeper
    
  init:
    hostname: init
    image: apachepulsar/pulsar:2.8.1
    volumes:
      - ./conf:/conf
      - ./scripts:/scripts
    command: bin/pulsar initialize-cluster-metadata \
          --cluster pulsar-cluster \
          --zookeeper zoo:2181 \
          --web-service-url localhost:8080 \
          --configuration-store zoo:2181 \
          --broker-service-url pulsar://broker:6650
    depends_on:
      - zoo

  bookie:
    hostname: bookie
    image: apachepulsar/pulsar:2.8.1
    ports:
      - "3181:3181"
    environment:
        BOOKIE_CONF: /conf/bookkeeper.conf
    volumes:
      - ./conf:/conf
      - ./scripts:/scripts
    command: bin/bookkeeper bookie
    depends_on:
      - init
    
  broker:
    hostname: broker
    image: apachepulsar/pulsar:2.8.1
    environment:
        PULSAR_BROKER_CONF: /conf/broker.conf
    ports:
      - "6660:6650"
      - "8090:8080"
    volumes:
      - ./conf:/conf
      - ./scripts:/scripts
    command: bin/pulsar broker
    depends_on:
      - bookie


  pulsar-proxy:
    image: apachepulsar/pulsar:2.8.1
    hostname: pulsar-proxy
    ports:
      - "6650:6650"
      - "8080:8080"
    environment:
        PULSAR_PROXY_CONF: "/conf/proxy.conf"
    volumes:
      - ./conf:/conf
      - ./scripts:/scripts
    command: bin/pulsar proxy 
    depends_on:
      - broker
