version: "3"

services:
  python:
    build:
      context: .
    restart: always
    devices:
      - "/dev/snd:/dev/snd"
    environment:
      - RASPBERRY_ID=1
      - COORDINATES_ID=1
      - IP_SERVER=192.168.1.58
