version: '3'

services:
  python:
    build:
      context: .
    restart: always
    devices:
      - "/dev/snd:/dev/snd"
    privileged: true
    security_opt:
      - seccomp:unconfined 
    cap_add: 
      - SYS_ADMIN
